-- ─────────────────────────────────────────────────────────────────────────────
-- portal_v29_onboarding_v2_catalogo.sql
--
-- GENERADO por scratchpad/gen-catalogo.cjs desde el fuente de
-- onboarding-korex-standalone.html. No editar a mano: para cambiar el catálogo
-- se usa el constructor de /admin/onboarding, que setea updated_by y por eso
-- queda protegido del `on conflict ... where updated_by is null` de abajo.
--
-- 4 bloques · 23 pasos · 125 preguntas
-- (93 obligatorias, 13 condicionales,
--  45 con micrófono, 62 con ejemplo)
--
-- El catálogo v1 (7 tramos / 66 preguntas) se DESACTIVA, no se borra:
-- onboarding_answers.qkey no tiene FK a propósito, así que las respuestas del
-- cliente de prueba sobreviven y simplemente dejan de contar para el progreso.
--
-- Además de las preguntas del HTML va una que no está en él: material_branding.
-- El paso 18 ofrece "Tengo logo, lo subo en PNG", "Tengo branding, lo adjunto"
-- y "Tengo tipografía, la subo a la carpeta", pero ninguna pantalla del
-- prototipo tiene dónde subirlo. Dejar tres promesas sin destino es peor que
-- agregar un dropzone opcional.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

-- ── 1 · Baja el catálogo v1 ──────────────────────────────────────────────────
update public.onboarding_questions set activa = false, updated_at = now()
 where activa and skey in (select skey from public.onboarding_sections where bkey is null);
update public.onboarding_sections set activa = false, updated_at = now()
 where activa and bkey is null;

-- ── 2 · Bloques ──────────────────────────────────────────────────────────────
insert into public.onboarding_bloques (bkey, orden, nombre, corto, titulo, descripcion, desbloquea, activa) values
  ('b1', 10, 'Bloque 1 · Arranque', 'Arranque', 'Ya estás dentro, formalmente.', 'Tu sesión reservada, tus datos y tu contrato. Lo administrativo terminó — ahora viene lo que construye tu negocio.', '{}'::text[], true),
  ('b2', 20, 'Bloque 2 · Estrategia', 'Estrategia', 'Con esto ya podemos escribir tu VSL y tus anuncios.', 'Tu foco, tu oferta, tu gente y tu historia. Es el corazón del proyecto y ya está cerrado.', '{/guiones,/embudos}'::text[], true),
  ('b3', 30, 'Bloque 3 · Operación', 'Operación', 'Tu infraestructura queda lista para el día 0.', 'Dominio, WhatsApp, accesos y compliance. Todo lo que suele frenar un lanzamiento, resuelto de entrada.', '{}'::text[], true),
  ('b4', 40, 'Bloque 4 · Materiales y arranque', 'Materiales', 'Terminaste. Ahora empezamos nosotros.', '', '{/material}'::text[], true)
on conflict (bkey) do update set orden = excluded.orden, nombre = excluded.nombre, corto = excluded.corto,
  titulo = excluded.titulo, descripcion = excluded.descripcion,
  desbloquea = excluded.desbloquea, activa = true, updated_at = now()
 where public.onboarding_bloques.updated_by is null;

-- ── 3 · Pasos ────────────────────────────────────────────────────────────────
insert into public.onboarding_sections (skey, bkey, orden, badge, eyebrow, titulo, subtitulo, para_que, icono,
   una_por_pantalla, minutos, checkpoint, promesa, intro_md, activa) values
  ('p00', 'b1', 10, '00', 'Primero lo primero', 'Agenda tu sesión de onboarding', 'Reserva ahora la videollamada en la que repasamos todo esto contigo. Completa el resto del onboarding antes de esa reunión: la usamos para resolver dudas, no para responderlo ahí.', 'Reservar la llamada ahora te asegura el lugar en la agenda del equipo — y todo lo demás avanza en paralelo.', 'M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z', false, 1, false, '', '', true),
  ('p01', 'b1', 20, '01', 'Sección 0 · datos administrativos', 'Empecemos por ti', 'Lo justo para formalizar el inicio: con estos datos armamos tu contrato y tu factura. Dos minutos y pasamos a lo importante.', 'Con esto emitimos tu contrato y tu factura, y no volvemos a molestarte con papeles.', 'M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8z', false, 7, false, '', '', true),
  ('p03', 'b2', 30, '03', 'Sección 1 · el rumbo', '¿Cuál es tu foco?', 'Solo una opción puede ser el foco principal. Esto ordena todo lo que viene: si eliges oportunidad, empezamos por ahí. Igual completarás lo básico del otro pilar para que entendamos tu empresa al 100%.', 'Define el mensaje principal de tus anuncios: producto u oportunidad, nunca los dos a la vez.', 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM12 11.6a.4.4 0 1 0 0 .8.4.4 0 0 0 0-.8z', false, 1, false, '', '', true),
  ('p04', 'b2', 40, '04', 'Sección 2 · lo esencial', 'Tu negocio', 'Información general que aplica a ambos focos. Con esto entendemos qué haces y a quién ayudas.', 'Es la base de todo lo que vamos a escribir: qué haces y a quién ayudas.', 'M4 7h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2zM8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M2 12h20', false, 6, false, '', '', true),
  ('p05', 'b2', 50, '05', 'Sección 3 · tu gente', 'Tu equipo y comunidad', 'Aplica sobre todo si tu foco incluye oportunidad de negocio, pero complétala igual.', 'Alimenta el bloque de comunidad de tu video y filtra a quién queremos atraer.', 'M17 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9.5 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75', false, 11, false, '', '', true),
  ('p4a', 'b2', 60, '4A', 'Sección 4A · tu oferta de producto', 'Tu producto', 'Completa si tu foco incluye producto. Si es oportunidad 100%, danos al menos lo básico para entender tu empresa.', 'Con esto armamos tu oferta de producto y el avatar al que le hablan los anuncios.', 'M21 8l-9-5-9 5v8l9 5 9-5V8zM3 8l9 5 9-5M12 13v9', false, 20, false, '', '', true),
  ('p4b', 'b2', 70, '4B', 'Sección 4B · tu oferta de oportunidad', 'Tu oportunidad de negocio', 'Completa si tu foco incluye oportunidad. Si es producto 100%, danos al menos lo básico.', 'Con esto armamos tu oferta de oportunidad y el guion de reclutamiento.', 'M22 7l-8.5 8.5-4-4L2 19M16 7h6v6', false, 15, false, '', '', true),
  ('p06', 'b2', 80, '06', 'Nuevo · para no adivinar a mitad de camino', '¿Por qué frente empezamos?', 'Elegiste trabajar los dos pilares. Si de la estrategia salen dos avatares, saber cuál lanza primero nos evita frenar el diseño con consultas — y a ti, esperas.', 'Saber cuál lanza primero evita frenar el diseño para consultarte a mitad de camino.', 'M6 3v12M18 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM6 21a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM15 6H9a3 3 0 0 0-3 3v3', false, 1, false, '', '', true),
  ('p07', 'b2', 90, '07', 'Sección 5 · cómo suena tu marca', 'Comunicación y tono', 'Esto define cómo hablan tus anuncios — y qué nunca deben decir. Los claims que marques como prohibidos se convierten en un filtro que revisa cada anuncio antes de grabarlo, para que Meta no te rechace nada.', 'Define cómo suenan tus anuncios y activa el filtro que evita que Meta te rechace nada.', 'M3 11l18-5v12L3 14v-3zM11.6 16.8a3 3 0 1 1-5.8-1.6', false, 8, false, '', '', true),
  ('p08', 'b2', 100, '08', 'Sección 6 · el terreno', 'Competencia y diferenciadores', 'Nos ayuda a posicionarte con claridad frente a quien ya está ahí.', 'Nos posiciona con claridad frente a quien ya está en tu mercado.', 'M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1zM4 22v-7', false, 3, false, '', '', true),
  ('p09', 'b2', 110, '09', 'Sección 7 · la más importante de todas', 'Tu historia y autoridad', 'Esta sección alimenta tu autoridad y tu conexión con la audiencia — y la conexión vende. En vez de escribir, háblanos: graba cada respuesta como si te estuvieran entrevistando. Lo transcribimos palabra por palabra, sin pulir. Cuanto más real y con más datos concretos, mejor.', 'Es la materia prima de tu video de ventas: tus palabras, sin pulir, son las que venden.', 'M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3zM19 10v2a7 7 0 0 1-14 0v-2M12 19v3', true, 24, false, '', '', true),
  ('p10', 'b2', 120, '10', 'Sección 8 · tus formularios de captación', 'Calificación del lead', 'Define cómo filtramos a la gente que entra por tus anuncios.', 'Configura el formulario que la gente completa antes de llegar a tu WhatsApp.', 'M22 3H2l8 9.46V19l4 2v-8.54L22 3z', false, 3, false, '', '', true),
  ('p11', 'b2', 130, '11', 'Sección 9 · lo que ya probaste', 'Experiencias en marketing', 'Aprendemos de lo que ya funcionó y evitamos repetir lo que no.', 'Reutilizamos lo que ya te funcionó y evitamos repetir lo que te costó dinero.', 'M12 8v4l3 2M3.05 11a9 9 0 1 1 .5 4M3 4v5h5', false, 3, false, '', '', true),
  ('p12', 'b3', 140, '12', 'Sección 10 · tu activo más valioso', 'Audiencia y segmentación', 'Tu base de datos es oro: con ella Meta encuentra a personas parecidas a tus mejores clientes y baja tu coste por lead.', 'Tu base de datos y tu Pixel bajan el coste por lead desde la primera semana.', 'M12 3c4.97 0 9 1.34 9 3s-4.03 3-9 3-9-1.34-9-3 4.03-3 9-3zM3 6v12c0 1.66 4.03 3 9 3s9-1.34 9-3V6M3 12c0 1.66 4.03 3 9 3s9-1.34 9-3', false, 3, false, '', '', true),
  ('p13', 'b3', 150, '13', 'Sección 11 · tu operación actual', 'Canales, proceso y presupuesto', 'Cómo vendes hoy y con qué recursos cuentas.', 'Con esto calculamos tu inversión diaria y diseñamos el embudo sobre tu proceso real.', 'M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6', false, 8, false, '', '', true),
  ('p14', 'b3', 160, '14', 'Sección 12 · dónde vivirá tu landing', 'Tu dominio', 'Definir esto ahora nos deja congelar la URL el día 0 — y eso desbloquea todo el montaje en paralelo mientras tú sigues con lo tuyo.', 'Congelar la URL hoy nos deja montar tu landing en paralelo.', 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM3 12h18M12 3c2.5 2.5 3.6 5.5 3.6 9s-1.1 6.5-3.6 9c-2.5-2.5-3.6-5.5-3.6-9S9.5 5.5 12 3z', false, 7, false, '', '', true),
  ('p15', 'b3', 170, '15', 'Sección 13 · contacto directo', 'Tu WhatsApp', 'Este número irá en los botones de contacto de tu landing y tus anuncios. Verifícalo bien — un dígito mal cuesta leads.', 'Es el número al que van a llegar los interesados: un dígito mal cuesta leads.', 'M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z', false, 4, false, '', '', true),
  ('p16', 'b3', 180, '16', 'Nuevo · para no frenar el lanzamiento', 'Accesos a Meta y redes', 'Estos accesos suelen aparecer al final y frenan el lanzamiento días enteros. Los resolvemos ahora, de una vez, y tu campaña no espera a nadie.', 'Los accesos son lo que más retrasa lanzamientos. Resolverlos ahora te ahorra días.', 'M21 2l-2 2M11.4 11.6a5 5 0 1 1-7.1 7.1 5 5 0 0 1 7.1-7.1zM11.4 11.6L15.5 7.5M15.5 7.5l3 3L22 7l-3-3-3.5 3.5z', false, 7, false, '', '', true),
  ('p17', 'b3', 190, '17', 'Nuevo · el trámite que corre en paralelo', 'Compliance de tu empresa', 'Algunas empresas exigen aprobar la publicidad de sus distribuidores antes de publicarla — un trámite que puede tardar semanas. Si es tu caso, lo iniciamos HOY en paralelo, para que no frene nada.', 'Si tu empresa aprueba publicidad, el trámite arranca hoy en paralelo.', 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4', false, 6, false, '', '', true),
  ('p18', 'b4', 200, '18', 'Sección 14 · tu material', 'Sube tus archivos', 'Arrastra aquí lo que tengas. Se sube directo a tu carpeta. Lo que no tengas hoy lo marcas como pendiente y tu landing sale igual: la completamos en cuanto llegue (V1 → V2). Fecha límite de materiales: día 3.', 'Tu material es lo que hace que todo salga con tu identidad y tu cara.', 'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M17 8l-5-5-5 5M12 3v12', false, 15, false, '', '', true),
  ('p19', 'b4', 210, '19', 'Nuevo · para no frenarnos cuando no estás', 'Tu delegado y tu comunicación', 'Sabemos que lideras y viajas mucho. Si tienes una persona de confianza que pueda decidir por ti en el día a día, el proyecto no se detiene cuando tú no puedes responder. Si trabajas solo, sáltate los tres primeros campos.', 'Una persona que pueda decidir por ti evita que el proyecto se detenga cuando viajas.', 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM16 11l2 2 4-4', false, 8, false, '', '', true),
  ('p20', 'b4', 220, '20', 'Sección 15 + agenda · lo que más acelera tu entrega', 'Tu grabación y HeyGen', 'Tu grabación es el único paso que solo puedes dar tú — todo lo demás lo adelantamos en paralelo. Reservándola ahora, tu reloj de 15 días arranca con fecha real. Y HeyGen nos permite generar anuncios sin pedirte grabar una y otra vez.', 'Tu grabación es el único paso que solo puedes dar tú. Reservarla pone fecha real al lanzamiento.', 'M23 7l-7 5 7 5V7zM14 5H3a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z', false, 3, false, '', '', true),
  ('p21', 'b4', 230, '21', 'Último paso · el control de calidad', 'Revisemos que no falte nada', 'Tu reloj de 15 días solo arranca cuando lo crítico está completo. Esto es lo que tienes cerrado y lo que queda pendiente — lo pendiente no te frena, pero cuanto antes llegue, antes despega todo.', 'Repasamos qué está cerrado y qué falta antes de arrancar el reloj.', 'M22 11.08V12a10 10 0 1 1-5.93-9.14M22 4l-10 10-3-3', false, 1, false, '', '', true)
on conflict (skey) do update set bkey = excluded.bkey, orden = excluded.orden, badge = excluded.badge,
  eyebrow = excluded.eyebrow, titulo = excluded.titulo, subtitulo = excluded.subtitulo,
  para_que = excluded.para_que, icono = excluded.icono,
  una_por_pantalla = excluded.una_por_pantalla, minutos = excluded.minutos,
  checkpoint = excluded.checkpoint, activa = true, updated_at = now()
 where public.onboarding_sections.updated_by is null;

-- ── 4 · Preguntas ────────────────────────────────────────────────────────────
insert into public.onboarding_questions (qkey, skey, pantalla, orden, label, sublabel, cabecera, cabecera_sub, ejemplo, placeholder,
   chips, qtype, opciones, voz, requerida, min_chars, largo_objetivo, max_opciones, input_mode, min_altura,
   info_kicker, info_titulo, info_cuerpo, archivo_cta, archivo_hint, archivo_accept, archivo_multiple,
   solo_dia, visible_si, bucket_key, target_count, target_kind, target_column, target_mode,
   peso, minutos, plantilla_ord, plantilla_ref, ayuda_md, activa) values
  ('sesion', 'p00', 0, 10, '', '', '', '', '', '',
   '[]'::jsonb, 'agenda', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 101, '00 · Agenda tu sesión de onboarding', '', true),
  ('datos_enviados', 'p01', 0, 10, '¿Enviaste los datos para firmar el contrato y realizar la factura?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, ya los envié","hint":"Seguimos con la parte importante"},{"value":"no","label":"No — los dejo aquí","hint":"Cuatro campos y listo"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 201, '01 · Empecemos por ti', '', true),
  ('dat_nombre', 'p01', 0, 20, 'Nombre completo', '', '', '', '', 'María Fernanda González Ruiz',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"datos_enviados","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 202, '01 · Empecemos por ti', '', true),
  ('dat_documento', 'p01', 0, 30, 'Número del documento de identidad', 'DNI, CI, NIF, RFC o el que corresponda en tu país.', '', '', '', '27.845.112',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"datos_enviados","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 203, '01 · Empecemos por ti', '', true),
  ('dat_email', 'p01', 0, 40, 'E-mail', 'A esta dirección te llega el contrato para firmar.', '', '', '', 'maria@marianutricion.com',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"datos_enviados","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 204, '01 · Empecemos por ti', '', true),
  ('dat_direccion', 'p01', 0, 50, 'Dirección completa, con código postal y país', '', '', '', '', 'Av. Pellegrini 1420, piso 3 · Rosario, Santa Fe · CP 2000 · Argentina',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 100,
   '', '', '', '', '', '', true,
   false, '{"qkey":"datos_enviados","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 205, '01 · Empecemos por ti', '', true),
  ('info_01_0_5', 'p01', 0, 60, 'La firma arranca tu reloj de 15 días', '', '', '', '', '',
   '[]'::jsonb, 'info', '[]'::jsonb, false, false, 0, 0, null, '', null,
   'Por qué te lo pedimos ahora', 'La firma arranca tu reloj de 15 días', 'Es lo que nos habilita a comprar tu dominio, abrir tu cuenta publicitaria y poner al equipo a escribir. Todo lo demás de este onboarding avanza en paralelo, pero la entrega se cuenta desde la firma.', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 206, '01 · Empecemos por ti', '', true),
  ('foco', 'p03', 0, 10, 'Elige tu foco principal', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"op100","label":"Oportunidad de negocio 100%","hint":"Todo el foco en reclutar para tu equipo"},{"value":"prod100","label":"Venta de producto 100%","hint":"Todo el foco en vender lo que ofreces"},{"value":"ambas_op","label":"Ambas — primero oportunidad","hint":"Reclutamiento como prioridad, producto después"},{"value":"ambas_prod","label":"Ambas — primero producto","hint":"Producto como prioridad, oportunidad después"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, 'strategy_pages', 'tipo', 'fill',
   1, 1, 301, '03 · ¿Cuál es tu foco?', '', true),
  ('negocio_nombre', 'p04', 0, 10, 'Nombre de tu negocio o proyecto', '', '', '', '', 'María González Nutrición',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, 'clients', 'company', 'fill',
   1, 1, 401, '04 · Tu negocio', '', true),
  ('negocio_paises', 'p04', 0, 20, '¿En qué países opera la empresa y dónde tienes más actividad hoy?', '', '', '', 'La empresa opera en 94 países. Yo tengo actividad real en Argentina (el 70% de mi equipo, sobre todo Rosario y Buenos Aires), Chile, México y una línea chica en España que arrancó el año pasado.', 'La empresa en 94 países · mi actividad: Argentina (70%), Chile, México',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 402, '04 · Tu negocio', '', true),
  ('negocio_destino', 'p04', 0, 30, 'Destino / Transformación: ¿a qué ayuda tu negocio exactamente, en una frase?', 'Una sola frase, en el idioma de tu cliente.', '', '', 'Ayudo a mujeres de 35 a 55 que se sienten hinchadas y sin energía a recuperar su cuerpo y su cabeza en 30 días, sin dejar de comer lo que les gusta.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 200, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 403, '04 · Tu negocio', '', true),
  ('negocio_explicacion', 'p04', 0, 40, '¿Cómo le explicarías el negocio a alguien que no lo conoce, en 2-3 minutos?', 'Puedes escribirlo o, mejor aún, grabarlo con tus palabras.', '', '', 'Le digo: ayudo a personas que están cansadas de cambiar horas por dinero a armar un ingreso desde el celular, sin dejar lo que hacen hoy. Trabajo con una empresa de nutrición que tiene 30 años en el mercado, y lo que hago es enseñarle a la gente a vender esos productos y a formar su propio equipo. No es magia ni es rápido: al principio le dedicas una hora por día y en seis meses, si le pones, ya tienes un ingreso que se nota. Yo empecé igual, trabajando de enfermera en un hospital público.', '',
   '["qué haces","para quién","cómo gana dinero la gente"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 404, '04 · Tu negocio', '', true),
  ('redes_personales', 'p05', 0, 10, 'Tu Instagram, redes y web personales', 'Si son más de una persona, pongan el de todos. Si eres dueño de empresa, los de la empresa.', '', '', 'Instagram personal: @maria.gonzalez.nutri (12.400 seguidores)
Instagram del equipo: @equipolibertad.ar
Facebook: /marianutricionrosario
TikTok: @marianutri (recién arranqué)
Web: todavía no tengo', 'https://instagram.com/…',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 501, '05 · Tu equipo y comunidad', '', true),
  ('red_tamano', 'p05', 0, 20, '¿Cuántas personas hay en tu red hoy? ¿En qué países, principalmente?', '', '', '', 'Somos 412 personas en total, pero activas de verdad unas 90. El 70% en Argentina, 15% en Chile, 10% en México y algunas sueltas en España.', '412 en total, 90 activas · 70% Argentina, 15% Chile, 10% México',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 502, '05 · Tu equipo y comunidad', '', true),
  ('equipo_nombre', 'p05', 0, 30, 'Si tu equipo tiene nombre, ¿cuál es? ¿Cómo surgió?', '', '', '', 'Se llama Equipo Libertad. Salió de una charla con las tres primeras chicas que sumé: las tres queríamos lo mismo, dejar de pedir permiso para ir a un acto escolar. Lo votamos por WhatsApp en 2020 y quedó.', 'Equipo Libertad — lo elegimos entre las tres primeras que sumé',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, false, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 503, '05 · Tu equipo y comunidad', '', true),
  ('equipo_valores', 'p05', 0, 40, '¿Qué valores definen a tu equipo? ¿Qué aporta a los nuevos integrantes?', '', '', '', 'Lo que nos define es que nadie se queda solo: tenemos un sistema de madrinas donde cada persona nueva tiene una asignada durante sus primeros 90 días. Somos muy de celebrar lo chico, la primera venta se festeja igual que un ascenso de rango. Y hay una regla que no se negocia: no se vende con mentiras ni se promete lo que no se puede cumplir. Eché a dos personas por eso. Quien entra se lleva formación real, un grupo que responde todos los días, y la tranquilidad de que si se cae, hay alguien que lo levanta.', '',
   '["cómo empezó","qué valores tienen","qué se lleva el que entra"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 800, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 504, '05 · Tu equipo y comunidad', '', true),
  ('equipo_cualidades', 'p05', 0, 50, '¿Qué cualidades tienen las personas que mejor funcionan en tu equipo?', 'No lo que buscas en teoría: lo que ves en los que realmente rinden.', '', '', 'Las que mejor funcionan son las que ya venían vendiendo algo, aunque sea ropa por catálogo o tortas por encargo: no les da vergüenza ofrecer. Casi todas tienen entre 35 y 50 y algo que las aprieta, una deuda, un hijo que empieza la facultad, algo concreto. Y son las que preguntan mucho al principio, las que te llenan de mensajes. Las que dicen «sí, dale, mándame todo» y no preguntan nada, no arrancan nunca.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 505, '05 · Tu equipo y comunidad', '', true),
  ('equipo_no_quiero', 'p05', 0, 60, '¿A qué tipo de persona NO quieres atraer?', 'Con esto excluimos gente de tus anuncios y no gastas dinero en quien no te sirve.', '', '', 'No quiero gente que busca hacerse rica sin trabajar, los que preguntan «¿cuánto gano sin hacer nada?». Tampoco los que ya están en otra compañía y quieren cambiar cada seis meses, esos rompen el equipo. No quiero menores de 25 en general, porque no tienen la disciplina ni la red de contactos. Y no quiero a los que vienen a discutir si esto es una estafa: no me interesa convencer a nadie.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 506, '05 · Tu equipo y comunidad', '', true),
  ('por_que_contigo', 'p05', 0, 70, '¿Por qué se unen contigo y no con otro líder de la misma empresa?', 'Piensa en lo que te dicen las personas que ya están en tu equipo.', '', '', 'Porque yo no desaparezco después de que firman. La mayoría te suma y te deja sola con un PDF. Yo tengo un grupo de WhatsApp donde respondo todos los días, hago una llamada grupal los martes a las 20h desde hace tres años, y a cada persona nueva la acompaño en sus primeras cinco ventas: me conecto con ella y hacemos la venta juntas. También armé un manual propio de 40 páginas con los guiones que a mí me funcionaron, que no es material de la empresa, es mío. Y algo que me dicen mucho: que soy honesta con los números. No prometo que se van a hacer millonarias en tres meses, les digo exactamente cuánto tardé yo y cuánto trabajé.', '',
   '["qué haces que otros no","qué te dicen los tuyos","qué armaste tú mismo"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, 'strategy_pages', 'punto_dif', 'fill',
   1, 1, 507, '05 · Tu equipo y comunidad', '', true),
  ('acompanamiento', 'p05', 0, 80, '¿Qué acompañamiento concreto das a quien entra a tu equipo?', 'Rituales, llamadas semanales, contenido, grupo de WhatsApp, sistema de duplicación, mentoría…', '', '', 'Los primeros 90 días tiene una madrina asignada que le responde por WhatsApp todos los días. La primera semana hacemos una videollamada de una hora donde armamos juntas su lista de contactos y su primer mensaje. Le doy mi manual de 40 páginas con los guiones. Todos los martes a las 20h hay capacitación en vivo por Zoom, y quedan grabadas en un Drive al que tiene acceso. Sus primeras cinco ventas las hacemos juntas: se conecta conmigo y yo la acompaño en la llamada. Después pasa al grupo general, donde medimos con una planilla semanal quién hizo cuántos contactos.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 508, '05 · Tu equipo y comunidad', '', true),
  ('producto_principal', 'p4a', 0, 10, '¿Cuál es el producto principal que quieres ofrecer?', '', '', '', 'Es un pack de nutrición celular de 30 días: un batido de proteína vegetal para el desayuno, un té termogénico y un aloe para el sistema digestivo. Está pensado para mujeres de 35 a 55 que se sienten hinchadas, sin energía y que ya probaron dietas que no les funcionaron. No es una dieta: reemplazas una comida y listo.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 600, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 601, '4A · Tu producto', '', true),
  ('producto_beneficios', 'p4a', 0, 20, 'Beneficios concretos: ¿cuál es el «después» tras usar este producto?', '', '', '', 'En 30 días la mayoría baja entre 3 y 6 kilos, pero lo que más me dicen es que duermen mejor y que se les fue el bajón de las 4 de la tarde. Dejan de sentirse hinchadas en la primera semana. Y hay algo que no está en el folleto: se vuelven a sacar fotos.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 602, '4A · Tu producto', '', true),
  ('producto_diferencial', 'p4a', 0, 30, 'Valor diferencial: ¿en qué se diferencia de lo que ya existe?', '', '', '', 'La empresa tiene certificación de calidad propia y estudios clínicos publicados, no es un batido de marca blanca. Y del lado mío: no vendo el producto suelto, va con un plan de comidas que armé yo y un grupo de seguimiento donde estoy todos los días. Lo que hace la diferencia no es el polvo, es que nadie lo hace sola.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 603, '4A · Tu producto', '', true),
  ('producto_usuarios', 'p4a', 0, 40, '¿Cuántas personas ya lo han usado (aprox.)?', '', '', '', '', '180 clientas mías, y unas 40.000 en el país',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, 'text', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 604, '4A · Tu producto', '', true),
  ('producto_mercado', 'p4a', 0, 50, 'Mercado al que te diriges', '', '', '', 'Mujeres de 35 a 55, mamás, que trabajan en relación de dependencia o tienen un emprendimiento chico. Argentina, Chile y Uruguay. Que ya intentaron bajar de peso antes y no lo lograron.', 'Mujeres de 35 a 55, mamás, Argentina · Chile · Uruguay',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 605, '4A · Tu producto', '', true),
  ('producto_precio', 'p4a', 0, 60, 'Precio del producto', '', '', '', '', 'Pack de inicio 89 USD · recompra mensual 75 USD',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 606, '4A · Tu producto', '', true),
  ('producto_condiciones', 'p4a', 0, 70, 'Condiciones (envíos, suscripción, recompra…)', '', '', '', 'Envío gratis a todo el país en 48-72 h. La primera compra tiene 15% de descuento si se suscriben a la recompra mensual, que se puede cancelar cuando quieran sin permanencia. Si compran dos packs, el segundo sale a 75.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 300, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 607, '4A · Tu producto', '', true),
  ('producto_garantia', 'p4a', 0, 80, '¿Hay garantía? ¿Tiempo y condiciones?', '', '', '', '30 días de devolución. Si no está conforme, devuelve los envases aunque estén vacíos y se le reintegra el 100%. Lo cubre la empresa, no yo.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 220, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 608, '4A · Tu producto', '', true),
  ('av_prod_sexo', 'p4a', 0, 90, 'Sexo', '', 'Avatar del producto', 'Piensa en quien ya lo compró, no en quien te gustaría que lo compre.', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"mujeres","label":"Mayormente mujeres","hint":""},{"value":"hombres","label":"Mayormente hombres","hint":""},{"value":"mixto","label":"Mixto","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 609, '4A · Tu producto', '', true),
  ('av_prod_edad', 'p4a', 0, 100, 'Rango de edad', '', '', '', '', '',
   '[]'::jsonb, 'chips_multi', '[{"value":"18-25","label":"18 a 25","hint":""},{"value":"25-35","label":"25 a 35","hint":""},{"value":"35-45","label":"35 a 45","hint":""},{"value":"45-55","label":"45 a 55","hint":""},{"value":"55+","label":"55 o más","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 610, '4A · Tu producto', '', true),
  ('av_prod_laboral', 'p4a', 0, 110, 'Situación laboral', '', '', '', 'Docentes, enfermeras, empleadas administrativas y algunas con un emprendimiento chico de comida o ropa. Casi todas con sueldo fijo que no les alcanza y doble jornada en casa.', 'Docentes, enfermeras, empleadas administrativas · sueldo fijo',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 611, '4A · Tu producto', '', true),
  ('av_prod_dolores', 'p4a', 0, 120, 'Dolores principales', 'Escríbelo como lo dice esa persona, no como lo dirías tú.', '', '', 'La mayoría llega diciendo lo mismo: «me miro al espejo y no me reconozco». Subieron 10 o 15 kilos después de los embarazos o de la menopausia, están todo el día cansadas, se levantan ya sin energía. Probaron de todo: la dieta de la nutricionista que abandonaron a la semana, el gimnasio al que fueron un mes, las pastillas que compraron por Instagram. Cada intento fallido les dejó la sensación de que el problema son ellas, que no tienen fuerza de voluntad. Y hay algo que casi ninguna dice en voz alta: dejaron de ir a eventos, de sacarse fotos, de tener intimidad con su pareja.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 130,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 612, '4A · Tu producto', '', true),
  ('av_prod_botones', 'p4a', 0, 130, 'Botones calientes — marca los que apliquen', '', '', '', '', '',
   '[]'::jsonb, 'chips_multi', '[{"value":"tiempo","label":"Tiempo extra","hint":""},{"value":"ingreso","label":"Ingreso extra","hint":""},{"value":"libertad","label":"Libertad financiera","hint":""},{"value":"viajar","label":"Viajar","hint":""},{"value":"desarrollo","label":"Desarrollo personal","hint":""},{"value":"jubilacion","label":"Jubilación","hint":""},{"value":"contribucion","label":"Contribución","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 613, '4A · Tu producto', '', true),
  ('producto_casos', 'p4a', 0, 140, 'Casos de éxito del producto (antes / después)', 'Idealmente en video, pero ahora cuéntanoslos. Importante: que sean del mismo avatar al que nos dirigimos.', '', '', 'Marcela, 48 años, de Rosario. Llegó pesando 89 kilos, con presión alta y tomando medicación. En 5 meses bajó 17 kilos y el médico le sacó una de las pastillas.

Vanina, 34, dos hijos chicos. No le importaba tanto el peso, estaba con agotamiento y caída de pelo post parto. A los dos meses me mandó un audio llorando porque se pudo poner el vestido de su casamiento. Bajó 8 kilos.

Fernando, 52, camionero, comía en la ruta, tenía prediabetes. Bajó 22 kilos en 8 meses y el último análisis le dio valores normales. Nadie le cree que es el mismo de la foto.', '',
   '["nombre y edad","cómo estaba antes","qué logró y en cuánto"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 614, '4A · Tu producto', '', true),
  ('op_explicacion', 'p4b', 0, 10, '¿Cómo explicas con tus palabras en qué consiste esta oportunidad?', '', '', '', 'Es armar tu propio negocio de nutrición sin tener que fabricar nada ni poner un local. Vendes productos de una empresa que ya tiene 31 años y, cuando le enseñas a otra persona a hacer lo mismo, cobras también por lo que ella vende. Se puede hacer desde el celular, una hora por día, sin dejar tu trabajo. No es un empleo: no tienes jefe ni horario, pero tampoco tienes sueldo asegurado — cobras por lo que haces.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 701, '4B · Tu oportunidad de negocio', '', true),
  ('op_que_busca', 'p4b', 0, 20, '¿Qué busca realmente la persona para querer formar parte?', '', '', '', 'No buscan «un negocio», buscan salir de algo. La mayoría quiere dejar de contar los días hasta el 10 y poder decidir su tiempo: llevar a los chicos al colegio, no pedir permiso para un acto escolar. Muchas también buscan pertenecer a algo, sentirse útiles otra vez — sobre todo las que se acaban de jubilar o quedaron sin trabajo.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 600, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 702, '4B · Tu oportunidad de negocio', '', true),
  ('op_diferencial', 'p4b', 0, 30, 'Valor diferencial y «highlights» frente a lo que ya existe', '', '', '', 'La empresa tiene 31 años y opera en 94 países, no es una startup que puede desaparecer. El plan de compensación paga desde la primera venta, no tienes que llegar a un rango para cobrar: la gente ve dinero en su primera semana y no abandona. No hay obligación de compra mensual mínima, que es lo que hunde a la gente en otras compañías. La recompra del producto es del 68%, o sea que armas un ingreso que se repite sin salir a buscar clientes nuevos todos los meses.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 800, null, '', 130,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 703, '4B · Tu oportunidad de negocio', '', true),
  ('op_mercado', 'p4b', 0, 40, 'Mercado al que nos dirigimos', '', '', '', 'Mujeres y hombres de 30 a 55, en Argentina, Chile y México, con trabajo pero sin margen: enfermeras, docentes, empleados de comercio, choferes. Gente que ya vendió algo alguna vez, aunque sea ropa por catálogo.', 'Mujeres y hombres de 30 a 55 · Argentina, Chile y México',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 704, '4B · Tu oportunidad de negocio', '', true),
  ('op_precio', 'p4b', 0, 50, 'Precio / modalidades para entrar', '', '', '', 'Kit de inicio básico 180 USD (incluye producto para el primer mes y la licencia). Kit de negocio 350 USD, que es el que recomiendo porque ya te deja stock para vender. Y hay uno de 1.200 USD para quien quiere arrancar con equipo. No hay cuota mensual obligatoria.', 'Kit básico 180 USD · kit de negocio 350 USD · sin cuota mensual',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 705, '4B · Tu oportunidad de negocio', '', true),
  ('av_op_sexo', 'p4b', 0, 60, 'Sexo', '', 'Avatar de la oportunidad', 'Piensa en quien ya está en tu equipo, no en quien te gustaría sumar.', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"mujeres","label":"Mayormente mujeres","hint":""},{"value":"hombres","label":"Mayormente hombres","hint":""},{"value":"mixto","label":"Mixto","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 706, '4B · Tu oportunidad de negocio', '', true),
  ('av_op_edad', 'p4b', 0, 70, 'Rango de edad', '', '', '', '', '',
   '[]'::jsonb, 'chips_multi', '[{"value":"18-25","label":"18 a 25","hint":""},{"value":"25-35","label":"25 a 35","hint":""},{"value":"35-45","label":"35 a 45","hint":""},{"value":"45-55","label":"45 a 55","hint":""},{"value":"55+","label":"55 o más","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 707, '4B · Tu oportunidad de negocio', '', true),
  ('av_op_laboral', 'p4b', 0, 80, 'Situación laboral', '', '', '', 'Empleadas con sueldo fijo que no alcanza, algunas con doble trabajo. También comerciantes que quedaron golpeados después de la pandemia y jubiladas recientes.', 'Empleadas con sueldo que no alcanza, comerciantes, jubiladas recientes',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 708, '4B · Tu oportunidad de negocio', '', true),
  ('av_op_dolores', 'p4b', 0, 90, 'Dolores principales', 'Sus palabras exactas, sin pulir.', '', '', '«Trabajo todo el día y no me alcanza.» «Estoy cansada de estar cansada.» «Quiero dejar de depender de mi sueldo.» «No tengo tiempo ni para mí.» «Me da vergüenza que mis amigas se enteren.» «¿Y esto realmente funciona o es como todo?» Y la que más duele: sienten que a esta altura de su vida ya no van a poder cambiar nada.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 130,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 709, '4B · Tu oportunidad de negocio', '', true),
  ('av_op_botones', 'p4b', 0, 100, 'Botones calientes — marca los que apliquen', '', '', '', '', '',
   '[]'::jsonb, 'chips_multi', '[{"value":"tiempo","label":"Tiempo extra","hint":""},{"value":"ingreso","label":"Ingreso extra","hint":""},{"value":"libertad","label":"Libertad financiera","hint":""},{"value":"viajar","label":"Viajar","hint":""},{"value":"desarrollo","label":"Desarrollo personal","hint":""},{"value":"jubilacion","label":"Jubilación","hint":""},{"value":"contribucion","label":"Contribución","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 710, '4B · Tu oportunidad de negocio', '', true),
  ('op_casos', 'p4b', 0, 110, 'Casos de éxito de la oportunidad (cómo les cambió la vida)', 'Personas distintas a las del producto. Nombre, cómo estaban antes, qué lograron y en cuánto tiempo.', '', '', 'Carolina, 41, docente de primaria en Mar del Plata. Entró en 2022 con doble turno en la escuela y sintiendo que se le iba la vida. Hoy factura 2.500 USD por mes y dejó uno de los dos turnos.

Damián, 37, tenía un local de repuestos que le iba mal después de la pandemia. Le daba vergüenza que sus amigos se enteraran; tardó tres semanas en decidirse. En un año armó un equipo de 30 personas y se permitió un viaje con la familia.

Silvina, 55, recién jubilada y deprimida porque sentía que ya no servía para nada. No vino por el dinero, vino por pertenecer a algo. Hoy es la que más vende del equipo.', '',
   '["quién era","cómo estaba antes","qué logró y en cuánto"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 711, '4B · Tu oportunidad de negocio', '', true),
  ('frente', 'p06', 0, 10, 'Elige el frente que lanza primero', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"op","label":"Primero el de oportunidad","hint":"Lanzamos el funnel de reclutamiento y luego el de producto"},{"value":"prod","label":"Primero el de producto","hint":"Lanzamos el funnel de producto y luego el de reclutamiento"},{"value":"korex","label":"El que esté más listo","hint":"Confío en el criterio de Korex: arranca el que tenga más activos cerrados"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"foco","in":["ambas_op","ambas_prod"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 801, '06 · ¿Por qué frente empezamos?', '', true),
  ('tono', 'p07', 0, 10, 'Ángulo y tono', 'Ej: formal, cercano, motivacional, analítico, comunidad que se apoya…', '', '', 'Cercano y directo, sin humo. Quiero que suene a una amiga que sabe de salud, no a una gurú. Me sirve el tono de comunidad («acá nadie se queda sola») y me molesta el tono de coach que grita. Nada de urgencia falsa.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 300, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 901, '07 · Comunicación y tono', '', true),
  ('palabras_no', 'p07', 0, 20, 'Palabras o expresiones que NO quieres que aparezcan', '', '', '', 'No quiero «adelgazar», «dieta milagro», «cuerpo perfecto», «antes y después» como titular, ni nada que haga sentir mal a nadie por su cuerpo. Tampoco «libertad financiera en 6 meses»: me parece una falta de respeto.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 250, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 902, '07 · Comunicación y tono', '', true),
  ('claims_si', 'p07', 0, 30, 'Claims o promesas PERMITIDOS por tu empresa', '', '', '', 'Se puede decir «ayuda a mejorar la digestión», «acompaña un estilo de vida saludable», «reemplazo de una comida». Se pueden mostrar testimonios si van con el descargo «resultados individuales».', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 250, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 903, '07 · Comunicación y tono', '', true),
  ('claims_no', 'p07', 0, 40, 'Claims o promesas NO PERMITIDOS', 'Alimenta el filtro anti-baneo que revisa cada anuncio antes de grabarlo.', '', '', 'La empresa prohíbe decir «cura», «trata», «adelgaza» y mencionar cualquier enfermedad. No se pueden mostrar cifras de ingresos propias sin el descargo legal. No se puede usar el logo de la empresa en anuncios pagos. Y nada de «ingresos garantizados».', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 300, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 904, '07 · Comunicación y tono', '', true),
  ('frases_cierre', 'p07', 0, 50, 'Frases que ya te funcionaron para cerrar gente', 'Escríbelas tal cual las dices, sin pulir — esto es oro puro para los anuncios.', '', '', '«No te estoy ofreciendo un trabajo más, te estoy ofreciendo dejar de pedir permiso.»
«Yo también pensé que era una estafa. Estuve seis meses evitando a la persona que me lo contó.»
«No necesitas saber vender, necesitas saber contar lo que te pasó.»
«¿Qué es lo peor que puede pasar? Que aprendas algo y no funcione. ¿Y lo mejor?»
«Si sigues igual dentro de un año, no va a ser por falta de una oportunidad.»', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 905, '07 · Comunicación y tono', '', true),
  ('objeciones', 'p07', 0, 60, 'Top 3-5 objeciones que más escuchas de prospectos', 'Cada objeción que nos cuentes la respondemos dentro de tu video.', '', '', '«Lo tengo que hablar con mi marido» es la número uno, y en realidad significa que no está convencida ella.
«No tengo tiempo», que me lo dicen justamente las que están más desesperadas por falta de tiempo.
«Yo no sirvo para vender» — la más fuerte en la parte de negocio: tienen miedo al ridículo delante de sus conocidos.
«¿Esto no es una pirámide?» — casi nadie lo dice así de frontal, lo insinúan.
«Ya probé de todo y nada me funcionó», que es más miedo a fracasar de nuevo que una objeción de precio.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 906, '07 · Comunicación y tono', '', true),
  ('competencia', 'p08', 0, 10, '¿Quiénes son tus principales competidores o referentes que te inspiran?', 'Nombres, cuentas o links. Uno por línea.', '', '', '@lauranutricion — misma empresa, España, muy buena en video
@vidaplenamlm — competencia directa, hacen mucho «antes y después»
Gabriela Ruiz — otra compañía, la referente del rubro en Argentina
Me inspira @doctormacarena por cómo explica sin vender', '@lauranutricion
@vidaplenamlm
Gabriela Ruiz',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1001, '08 · Competencia y diferenciadores', '', true),
  ('ventajas', 'p08', 0, 20, '¿Qué ventajas competitivas quieres destacar frente a ellos?', '', '', '', 'Ellos venden el «baja 10 kilos en 10 días» y viven de la foto del antes y después. Yo quiero que se note que acá no hay milagro: hay un método de 30 días, un acompañamiento real y resultados que se sostienen. Y quiero destacar que soy enfermera, tengo formación en salud: no soy alguien que se puso a vender batidos de un día para el otro.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1002, '08 · Competencia y diferenciadores', '', true),
  ('h1', 'p09', 0, 10, '¿A qué te dedicabas antes de este negocio? De dónde vienes', '', '', '', 'Trabajé 14 años como enfermera en un hospital público. Turnos de 12 horas, guardias los fines de semana, y aun así no me alcanzaba para pagar el alquiler y la escuela de mis dos hijos. Me levantaba a las 5 de la mañana y volvía cuando ya estaban dormidos. Llegué a tener tres trabajos: el hospital, cuidados a domicilio los sábados y vendía ropa por catálogo. Estaba agotada todo el tiempo y sentía que por más que trabajara, nunca iba a salir de ahí. Lo que más me dolía no era el dinero, era perderme la infancia de mis hijos.', '',
   '["a qué te dedicabas","cuántas horas trabajabas","qué te dolía de esa vida"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1101, '09 · Tu historia y autoridad', '', true),
  ('h2', 'p09', 1, 10, '¿Hace cuánto iniciaste en el negocio que haces hoy?', '', '', '', 'Arranqué en marzo de 2019, así que van poco más de 7 años. Los primeros ocho meses fueron casi nulos, empecé a facturar en serio a fines de 2019.', 'Marzo de 2019, van 7 años',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1121, '09 · Tu historia y autoridad', '', true),
  ('h3', 'p09', 2, 10, '¿Por qué empezaste? Cuenta tu dolor, tu botón caliente — con contexto real', 'Esta respuesta es la que abre tu video de ventas. No hace falta que suene bonito.', '', '', 'Fue en marzo de 2019. Mi hijo menor tuvo un problema de salud y necesitaba un tratamiento que no cubría la obra social. Costaba lo que yo ganaba en cuatro meses. Tuve que pedirle dinero prestado a mi hermana y todavía me acuerdo de la vergüenza que sentí. Esa noche entendí que el problema no era que trabajara poco, era que estaba cambiando tiempo por dinero y el tiempo se me estaba acabando. Una compañera del hospital me venía hablando del negocio hacía meses y yo la evitaba, pensaba que era una estafa. La llamé al día siguiente. Empecé sin creerla del todo, con miedo a que se rieran de mí, pero con la certeza de que no podía seguir como estaba.', '',
   '["qué pasó exactamente","cómo te sentías","qué te decidió"]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 1200, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1141, '09 · Tu historia y autoridad', '', true),
  ('h4', 'p09', 3, 10, '¿Qué resultados de dinero y materiales has logrado?', 'Con números concretos. Si tu empresa no permite mostrar cifras, igual cuéntanoslas: nosotros sabemos cómo decirlo sin romper la norma.', '', '', 'Hoy facturo entre 6.000 y 8.000 dólares por mes, con meses de 11.000 en campaña. Tengo mi casa propia desde hace dos años, la pagué con el negocio. Cambié el auto en 2024. El año pasado me llevé a mis dos hijos a Cancún, el primer viaje de mi vida en avión, y pagué todo sin pedirle dinero a nadie. También le pago la prepaga a mi mamá.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1161, '09 · Tu historia y autoridad', '', true),
  ('h5', 'p09', 4, 10, '¿Qué resultados NO materiales has logrado?', 'Lo que ganaste que no se compra. Suele ser lo que más conecta.', '', '', 'Dejé el hospital en enero de 2021 y ese día lloré en el estacionamiento. Hoy llevo a mis hijos al colegio todas las mañanas y los busco. Mi hija me dijo «mamá, ahora estás siempre» y esa frase vale más que cualquier cifra. Y cambió algo adentro mío: dejé de pedir permiso. Antes tenía que rogar por un franco para un acto escolar; hoy decido yo. Me volví alguien a quien otras mujeres le piden consejo, y eso no lo tenía.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1181, '09 · Tu historia y autoridad', '', true),
  ('h6', 'p09', 5, 10, '¿Qué estilo de vida te permitió? Cuenta una anécdota', 'Una escena concreta, con día y lugar. Las anécdotas se ven; los adjetivos no.', '', '', 'En octubre del año pasado mi hijo tenía el acto de fin de curso un martes a las 10 de la mañana. Antes eso era imposible: significaba pedir un franco tres semanas antes y que me lo negaran. Ese día lo llevé, me quedé en la primera fila, filmé todo y después nos fuimos a desayunar los tres. Volví a casa a las 12 y trabajé dos horas desde el celular. Eso es lo que cambió: no la casa ni el auto, es poder estar donde tengo que estar.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1201, '09 · Tu historia y autoridad', '', true),
  ('h7', 'p09', 6, 10, '¿Cuántas personas tienes en tu red?', '', '', '', '412 personas en total, unas 90 activas de verdad. En cuatro países: Argentina, Chile, México y España.', '412 en total, unas 90 activas, en 4 países',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1221, '09 · Tu historia y autoridad', '', true),
  ('h8', 'p09', 7, 10, '¿Qué cualidades tienen mayoritariamente esas personas?', '', '', '', 'Son mujeres de 35 a 50, casi todas mamás, con trabajo pero sin margen. Muchas ya habían vendido algo antes: ropa por catálogo, tortas, cosmética. Tienen en común que no les da vergüenza ofrecer y que necesitan algo concreto: una deuda, un hijo que empieza la facultad. Y las mejores son las que preguntan mucho al principio.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1241, '09 · Tu historia y autoridad', '', true),
  ('h9', 'p09', 8, 10, '¿A qué tipo de persona NO quieres en tu negocio?', '', '', '', 'A los que buscan hacerse ricos sin trabajar, los del «¿cuánto gano sin hacer nada?». Tampoco a los que ya están en otra compañía y cambian cada seis meses: rompen el equipo. No quiero menores de 25 en general. Y no quiero a los que vienen a discutir si esto es una estafa: no me interesa convencer a nadie.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 500, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1261, '09 · Tu historia y autoridad', '', true),
  ('h10', 'p09', 9, 10, '¿A quién SÍ quieres en tu negocio?', '', '', '', 'Mujeres de 35 a 55, mamás, que trabajan en relación de dependencia o tienen un emprendimiento chico. En Argentina, Chile o Uruguay. Que sean activas en redes, que comenten cosas, no las que solo miran. Y sobre todo: gente que quiera resolver algo, no gente que quiera quejarse.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 600, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1281, '09 · Tu historia y autoridad', '', true),
  ('h11', 'p09', 10, 10, '¿Puntos diferenciales frente a otras oportunidades similares?', 'Lo que hace que alguien se quede contigo y no con otro líder de la misma empresa.', '', '', 'Yo no desaparezco después de que firman. La mayoría te suma y te deja sola con un PDF. Tengo un grupo de WhatsApp donde respondo todos los días, una llamada grupal los martes a las 20h desde hace tres años, y a cada persona nueva la acompaño en sus primeras cinco ventas. Armé un manual propio de 40 páginas que no es material de la empresa, es mío. Y soy honesta con los números: no prometo millones en tres meses, digo exactamente cuánto tardé yo.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 900, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1301, '09 · Tu historia y autoridad', '', true),
  ('h12', 'p09', 11, 10, '¿Qué edad tienes?', '', '', '', '', '43',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, 'numeric', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1321, '09 · Tu historia y autoridad', '', true),
  ('h13', 'p09', 12, 10, '¿Cómo le explicas a alguien, en breve, el negocio que haces?', 'Como se lo dirías a un vecino en el ascensor. Esto se convierte casi textual en uno de tus anuncios.', '', '', 'Le digo: ayudo a personas que están cansadas de cambiar horas por dinero a armar un ingreso desde el celular, sin dejar lo que hacen hoy. Trabajo con una empresa de nutrición que tiene 30 años en el mercado, y lo que hago es enseñarle a la gente a vender esos productos y a formar su propio equipo. No es magia ni es rápido: al principio le dedicas una hora por día y en seis meses, si le pones, ya tienes un ingreso que se nota. Yo empecé igual, trabajando de enfermera.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 600, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1341, '09 · Tu historia y autoridad', '', true),
  ('h14', 'p09', 13, 10, '¿Algo más que quieras que sepamos?', 'Lo que no te preguntamos y crees que importa.', '', '', 'Dos cosas. Una: no quiero que se me venda como «la enfermera que se hizo rica», porque no es verdad y me da vergüenza. Prefiero «la enfermera que dejó el hospital». Y dos: mi hija mayor tiene 16 y a veces aparece en mis videos; me gustaría que no se use su cara en anuncios pagos.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 600, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1361, '09 · Tu historia y autoridad', '', true),
  ('aut_hitos', 'p09', 14, 10, 'Hitos, premios, entrevistas, conferencias', '', 'Autoridad pública', 'Lo usamos en la introducción de tu video. No te achiques: acá corresponde contar lo que lograste.', 'Soy rango diamante desde 2023. Gané el premio a mejor equipo del país en 2024. Hablé en el escenario del evento anual de la empresa en Miami el año pasado, delante de 4.000 personas.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 250, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1381, '09 · Tu historia y autoridad', '', true),
  ('aut_medios', 'p09', 14, 20, 'Apariciones en medios, podcasts, eventos', '', '', '', 'Me entrevistaron en el programa de la mañana de Radio 2 de Rosario (dos veces), y estuve en el podcast «Mujeres que Facturan» en 2024. Nada de TV todavía.', 'Radio 2 Rosario (2 veces) · podcast Mujeres que Facturan, 2024',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, false, 0, 0, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1382, '09 · Tu historia y autoridad', '', true),
  ('aut_reconocimientos', 'p09', 14, 30, 'Reconocimientos en la empresa o industria', '', '', '', 'Top 10 de facturación del país tres años seguidos. Reconocimiento «Líder Formadora» 2024 por cantidad de personas que subieron de rango en mi equipo. Y soy una de las 12 personas del consejo de líderes de la compañía en Argentina.', 'Top 10 de facturación del país 3 años seguidos · Líder Formadora 2024',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, false, 0, 0, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1383, '09 · Tu historia y autoridad', '', true),
  ('objetivo_lead', 'p10', 0, 10, '¿Cuál es tu objetivo actual?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"volumen","label":"Más volumen","hint":"Atraer más leads aunque sean menos cualificados"},{"value":"calidad","label":"Más calidad","hint":"Cualificar en el embudo: llegan menos pero mejores al cierre"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1201, '10 · Calificación del lead', '', true),
  ('preguntas_lead', 'p10', 0, 20, '¿Qué preguntas te ayudarían a cerrar más fácil cuando el prospecto llega?', 'Dos o tres. Las ponemos en el formulario que completan antes de contactarte.', '', '', '¿Hace cuánto que estás intentando resolver esto?
¿Cuánto podrías invertir por mes en tu salud o en tu negocio?
¿Cuántas horas por día le podrías dedicar?
¿Estás en Argentina, Chile o Uruguay?', '¿Hace cuánto que intentas resolver esto?
¿Cuánto podrías invertir por mes?
¿Cuántas horas al día le dedicarías?',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, true, 0, 0, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1202, '10 · Calificación del lead', '', true),
  ('camp_ok', 'p11', 0, 10, '¿Alguna campaña que te haya dado BUENOS resultados?', 'Cuéntanos al detalle cómo la hicieron. Si nunca hiciste, dilo.', '', '', 'Hice un sorteo en Instagram en 2023 que me trajo 300 seguidores y 12 ventas. El anuncio era un video mío hablando a cámara contando mi caso, sin producción, grabado con el celular en la cocina. Gasté 80 dólares en 10 días. Lo que creo que funcionó fue que no parecía publicidad.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 350, null, '', 120,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1301, '11 · Experiencias en marketing', '', true),
  ('camp_no', 'p11', 0, 20, '¿Campañas que NO dieron resultados?', 'Por encima, qué errores se cometieron.', '', '', 'Puse 200 dólares en anuncios con una foto del producto y el precio. Cero ventas. Después entendí que a nadie le importa el producto, les importa lo que les pasa a ellas. También probé con una agencia que me hizo videos muy producidos y no funcionaron: se veían a kilómetros que eran un anuncio.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 300, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1302, '11 · Experiencias en marketing', '', true),
  ('bbdd', 'p12', 0, 10, '¿Tienes bases de datos de emails o teléfonos de clientes?', 'Con ellas creamos audiencias «similares» y llegamos más fácil al público correcto.', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, la subo a mi carpeta","hint":""},{"value":"ayuda","label":"Sí, pero necesito ayuda para exportarla","hint":""},{"value":"no","label":"No tengo","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1401, '12 · Audiencia y segmentación', '', true),
  ('pixel', 'p12', 0, 20, '¿Tienes Pixel de Meta o eventos de conversión instalados?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, ya instalado","hint":""},{"value":"no","label":"No / no lo sé","hint":"Nosotros lo configuramos"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1402, '12 · Audiencia y segmentación', '', true),
  ('web', 'p13', 0, 10, '¿Tienes web o landing activa? Enlace/s', '', '', '', 'Tengo una tienda vieja en Tiendanube que no uso: marianutricion.mitiendanube.com. Y un linktree que sí uso: linktr.ee/marianutri', 'https://minegocio.com
linktr.ee/miusuario',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, false, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1501, '13 · Canales, proceso y presupuesto', '', true),
  ('proceso_venta', 'p13', 0, 20, '¿Cómo es tu proceso de ventas completo, de desconocido a cliente?', '', '', '', 'Me escriben por Instagram o WhatsApp, casi siempre preguntando el precio. Yo no doy precio de entrada: les hago tres preguntas para entender qué les pasa. Si veo que califica, le mando un audio de dos minutos contándole mi caso y le propongo una videollamada de 20 minutos. En la llamada le muestro el plan, le cuento testimonios parecidos al suyo y ahí sí le paso el precio. Cierro alrededor del 40% de las llamadas. A las que no cierran las paso a una lista y les mando contenido una vez por semana; varias compran dos o tres meses después.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 700, null, '', 180,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1502, '13 · Canales, proceso y presupuesto', '', true),
  ('quien_graba', 'p13', 0, 30, '¿Quién graba los anuncios?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"yo","label":"Yo","hint":""},{"value":"equipo","label":"Alguien de mi equipo","hint":""},{"value":"ia","label":"Quiero que lo haga la IA","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1503, '13 · Canales, proceso y presupuesto', '', true),
  ('lead_magnet', 'p13', 0, 40, '¿Tienes algo gratis para regalar?', 'Un PDF, una clase, una guía. Si no tienes, lo armamos nosotros.', '', '', 'Tengo una guía en PDF de 7 días de desayunos saludables que armé yo, la uso en Instagram y funciona bien. También hago un reto de 5 días por WhatsApp dos veces al año.', 'Guía en PDF de 7 días de desayunos saludables',
   '[]'::jsonb, 'abierta', '[]'::jsonb, false, false, 0, 0, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1504, '13 · Canales, proceso y presupuesto', '', true),
  ('objetivo_campana', 'p13', 0, 50, 'Objetivo principal de la campaña', '', '', '', 'Quiero 20 personas nuevas por mes en llamada, calificadas, para cerrar 8. Hoy consigo 5 o 6 llamadas por mes y todas son de mi círculo o referidos.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, true, 0, 250, null, '', 90,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1505, '13 · Canales, proceso y presupuesto', '', true),
  ('presupuesto', 'p13', 0, 60, 'Presupuesto mensual para publicidad', 'Es lo que se le paga a Meta, aparte de nuestro servicio.', '', '', '', '',
   '[]'::jsonb, 'presupuesto', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, 'clients', 'ads_budget_monthly', 'overwrite',
   1, 1, 1506, '13 · Canales, proceso y presupuesto', '', true),
  ('dominio', 'p14', 0, 10, 'Nombre de dominio deseado para la landing', 'Sin www ni https. Ej: tunegocio.com', '', '', '', 'marianutricion.com',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, 'strategy_pages', 'official_domain', 'fill',
   1, 1, 1601, '14 · Tu dominio', '', true),
  ('dominio_propio', 'p14', 0, 20, '¿Ya eres propietario de ese dominio?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, ya lo tengo registrado","hint":""},{"value":"no","label":"No, todavía no lo registré","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1602, '14 · Tu dominio', '', true),
  ('dominio_donde', 'p14', 0, 30, '¿Dónde está registrado?', 'Te pediremos acceso o un cambio de DNS — lo coordinamos por el grupo.', '', '', '', 'GoDaddy / Namecheap / Hostinger',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"dominio_propio","in":["si"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1603, '14 · Tu dominio', '', true),
  ('dominio_quien', 'p14', 0, 40, '¿Quién lo registra?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"korex","label":"Lo registran ustedes","hint":"Compra y configuración en una sola tarea — lo más rápido"},{"value":"yo","label":"Lo registro yo","hint":"Te pasamos las instrucciones exactas"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"dominio_propio","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1604, '14 · Tu dominio', '', true),
  ('dominio_alt', 'p14', 0, 50, '2 alternativas por si tu preferido no está disponible', '', '', '', '', 'marianutricion.com.ar, nutricionconmaria.com',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1605, '14 · Tu dominio', '', true),
  ('whatsapp', 'p15', 0, 10, 'Número de WhatsApp para los botones', 'Con código de país. Ej: +34 600 123 456 / +54 9 11 1234 5678', '', '', '', '+54 9 341 555 1234',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, true, 0, 0, null, 'tel', null,
   '', '', '', '', '', '', true,
   false, null, null, null, 'strategy_pages', 'whatsapp_leads', 'overwrite',
   1, 1, 1701, '15 · Tu WhatsApp', '', true),
  ('whatsapp_quien', 'p15', 0, 20, '¿Quién atiende ese WhatsApp cuando lleguen los leads?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"yo","label":"Yo directamente","hint":""},{"value":"equipo","label":"Alguien de mi equipo","hint":"Dinos quién en el campo de abajo"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1702, '15 · Tu WhatsApp', '', true),
  ('whatsapp_persona', 'p15', 0, 30, '¿Quién y en qué horario?', '', '', '', '', 'María José, mi asistente, de 9 a 21h',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"whatsapp_quien","in":["equipo"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1703, '15 · Tu WhatsApp', '', true),
  ('bm', 'p16', 0, 10, '¿Tienes Business Manager de Meta?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí — comparto el acceso","hint":"Te pediremos el ID en la sesión de configuración"},{"value":"no","label":"No / no lo sé","hint":"Lo creamos contigo en la sesión"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1801, '16 · Accesos a Meta y redes', '', true),
  ('bloqueos', 'p16', 0, 20, '¿Tu cuenta publicitaria tiene o tuvo bloqueos, rechazos o restricciones?', 'Saberlo ahora nos evita descubrirlo el día del lanzamiento.', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"limpia","label":"No, está limpia","hint":""},{"value":"problemas","label":"Sí, tuvo problemas","hint":"Cuéntanos brevemente abajo"},{"value":"sin_cuenta","label":"No tengo cuenta publicitaria","hint":"Activamos hoy el proceso estándar de creación"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1802, '16 · Accesos a Meta y redes', '', true),
  ('bloqueos_detalle', 'p16', 0, 30, '¿Qué pasó?', '', '', '', 'En 2023 me rechazaron tres anuncios por «promesas de salud» y me restringieron la cuenta una semana. Después de eso no volví a pautar. Nunca me la inhabilitaron del todo.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 200, null, '', 100,
   '', '', '', '', '', '', true,
   false, '{"qkey":"bloqueos","in":["problemas"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1803, '16 · Accesos a Meta y redes', '', true),
  ('fanpage', 'p16', 0, 40, '¿Tienes FanPage de Facebook vinculada a tu Instagram?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, ya vinculadas","hint":""},{"value":"nose","label":"Tengo FanPage pero no sé si está vinculada","hint":""},{"value":"no","label":"No tengo FanPage","hint":"La creamos ahora, no en el sprint de lanzamiento"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1804, '16 · Accesos a Meta y redes', '', true),
  ('info_16_0_4', 'p16', 0, 50, 'Una cuenta nueva necesita unos 4 días de maduración', '', '', '', '', '',
   '[]'::jsonb, 'info', '[]'::jsonb, false, false, 0, 0, null, '', null,
   'Se activa el proceso de creación de cuentas', 'Una cuenta nueva necesita unos 4 días de maduración', 'Al finalizar tu onboarding arrancamos hoy mismo el procedimiento estándar de creación de cuentas FB/IG: carga de seguidores y calentamiento. Por eso lo disparamos ahora y no en el sprint de lanzamiento. No tienes que hacer nada más.', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 1805, '16 · Accesos a Meta y redes', '', true),
  ('sesion_meta', 'p16', 0, 60, 'Agenda tu sesión de configuración de Meta con nuestro equipo', '30 minutos: dejamos Business Manager, cuenta, FanPage y accesos cerrados de una vez.', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"agendar","label":"Agendar ahora","hint":"Elegirás fecha junto con la de tu grabación, al final"},{"value":"grupo","label":"Coordinarlo por el grupo de WhatsApp","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1806, '16 · Accesos a Meta y redes', '', true),
  ('compliance', 'p17', 0, 10, '¿Tu empresa exige aprobar la publicidad antes de publicarla?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, tiene proceso de compliance","hint":""},{"value":"no","label":"No que yo sepa","hint":""},{"value":"nose","label":"No lo sé","hint":"Lo averiguamos contigo esta semana — mejor ahora que después"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1901, '17 · Compliance de tu empresa', '', true),
  ('compliance_contacto', 'p17', 0, 20, 'Contacto de compliance', '', '', '', '', 'Depto. de Marketing — legal@empresa.com',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"compliance","in":["si"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1902, '17 · Compliance de tu empresa', '', true),
  ('compliance_tiempos', 'p17', 0, 30, '¿Qué tiempos suele manejar?', '', '', '', '', 'Unos 5 días hábiles',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"compliance","in":["si"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 1903, '17 · Compliance de tu empresa', '', true),
  ('compliance_material', 'p17', 0, 40, '¿Tienes materiales o claims YA aprobados por tu empresa?', 'Si existen aprobaciones previas, las reutilizamos y ganamos semanas.', '', '', 'Tengo un PDF con los claims aprobados de 2024 y tres videos de producto que la empresa autorizó para redes. Los subo a la carpeta.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 200, null, '', 100,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 1904, '17 · Compliance de tu empresa', '', true),
  ('logo', 'p18', 0, 10, 'Logo', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Tengo logo","hint":"Lo subo en PNG y alta resolución"},{"value":"no","label":"No tengo","hint":"¿Alrededor de quién lo hacemos: tu nombre, el del equipo o el de la empresa?"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2001, '18 · Sube tus archivos', '', true),
  ('logo_alrededor', 'p18', 0, 20, '¿Alrededor de qué nombre lo armamos?', '', '', '', '', 'Mi nombre: María González',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"logo","in":["no"]}'::jsonb, null, null, null, null, 'fill',
   1, 1, 2002, '18 · Sube tus archivos', '', true),
  ('paleta', 'p18', 0, 30, 'Paleta de colores', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"empresa","label":"Uso los colores de la empresa","hint":""},{"value":"propios","label":"Mis colores preferidos son…","hint":""},{"value":"branding","label":"Tengo branding, lo adjunto","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2003, '18 · Sube tus archivos', '', true),
  ('paleta_detalle', 'p18', 0, 40, '¿Cuáles?', '', '', '', '', 'Azul marino (#0B1E3F) y dorado (#C9A227), fondo blanco',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, '{"qkey":"paleta","in":["propios"]}'::jsonb, null, null, 'clients', 'brand_colors', 'overwrite',
   1, 1, 2004, '18 · Sube tus archivos', '', true),
  ('tipografia', 'p18', 0, 50, 'Tipografía', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Tengo, la subo a la carpeta","hint":""},{"value":"no","label":"No tengo, definan ustedes","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2005, '18 · Sube tus archivos', '', true),
  ('info_18_0_5', 'p18', 0, 60, 'Usa un paquete Korex por nicho y arranca hoy', '', '', '', '', '',
   '[]'::jsonb, 'info', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '¿Sin branding propio?', 'Usa un paquete Korex por nicho y arranca hoy', 'Paquetes de identidad ya validados por sector: paleta, tipografías y estilo listos desde el día 0. Tu funnel no espera decisiones de diseño — y si luego quieres algo a medida, se ajusta en la V2.', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 2006, '18 · Sube tus archivos', '', true),
  ('paquete', 'p18', 0, 70, 'Elige un paquete si quieres arrancar con uno', '', '', '', '', '',
   '[]'::jsonb, 'chips_multi', '[{"value":"mlm","label":"Networkers / MLM","hint":""},{"value":"cripto","label":"Inversión / Cripto","hint":""},{"value":"viajes","label":"Viajes / Lifestyle","hint":""},{"value":"salud","label":"Salud / Bienestar","hint":""},{"value":"belleza","label":"Belleza / Estética","hint":""}]'::jsonb, false, false, 0, 0, 1, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2007, '18 · Sube tus archivos', '', true),
  ('material_branding', 'p18', 1, 5, 'Logo, colores y tipografía', 'Lo mejor es el logo en PNG con fondo transparente o el archivo original.', 'Tu marca', 'Si tenés logo, paleta o tipografía propios, subilos acá y los usamos tal cual.', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', 'Subí tu logo y tu branding', 'PNG, SVG, AI o el PDF de manual de marca.', 'image/*,.pdf,.ai,.svg,.eps', true,
   false, null, 'branding', null, null, null, 'fill',
   1, 1, 2020, '18 · Sube tus archivos', '', true),
  ('material_autoridad', 'p18', 1, 10, 'Fotos tuyas de autoridad', '5 fotos donde se te vea bien la cara. Las usamos en la portada de tus videos y en tu página.', 'Tus fotos', 'Con fotos del celular alcanza: buena luz, de frente, sin filtros.', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', 'Sube tus fotos', 'Puedes subirlas todas juntas.', 'image/*', true,
   false, null, 'autoridad', 5, null, null, 'fill',
   1, 1, 2021, '18 · Sube tus archivos', '', true),
  ('material_lifestyle', 'p18', 1, 20, 'Fotos de tu estilo de vida', 'Viajes, familia, eventos, premios. Son las que más conectan en los anuncios.', '', '', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', 'Sube las que quieras', 'Sin límite. Cuantas más, mejor.', 'image/*', true,
   false, null, 'estilo_vida', null, null, null, 'fill',
   1, 1, 2022, '18 · Sube tus archivos', '', true),
  ('material_producto', 'p18', 1, 30, 'Fotos de tu producto', 'El producto solo, en uso, y el pack completo si lo tienes.', '', '', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', 'Sube las fotos de producto', 'Si las tiene tu empresa, sirven igual.', 'image/*', true,
   false, null, 'productos', null, null, null, 'fill',
   1, 1, 2023, '18 · Sube tus archivos', '', true),
  ('material_empresa_files', 'p18', 1, 40, 'PDF o material de tu empresa', 'Presentación, plan de compensación, catálogo, fotos de eventos corporativos.', '', '', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', 'Sube el material', 'PDF, imágenes, links en un documento: lo que tengas.', '*', true,
   false, null, 'empresa', null, null, null, 'fill',
   1, 1, 2024, '18 · Sube tus archivos', '', true),
  ('info_18_2_0', 'p18', 2, 10, 'Qué le pides a cada persona', '', '', '', '', '',
   '[]'::jsonb, 'info', '[]'::jsonb, false, false, 0, 0, null, '', null,
   'Guion para tus 3 testimonios', 'Qué le pides a cada persona', 'Un video horizontal corto respondiendo: nombre y edad, a qué se dedicaba, país · en qué situación estaba antes · cómo te conoció y hace cuánto · qué dudas o creencias limitantes tenía · cómo está ahora, qué logró y cómo se siente. Que cada persona sepa que es un testimonio y dé su consentimiento. De producto por un lado y de oportunidad por el otro: tienen que ser personas distintas.', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 2041, '18 · Sube tus archivos', '', true),
  ('material_testimonios', 'p18', 2, 20, 'Tus 3 testimonios', 'Video horizontal, con buena luz. Si todavía no los tienes, sigue de largo y súbelos cuando estén.', '', '', '', '',
   '[]'::jsonb, 'archivos', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', 'Sube tus testimonios', 'Video u — si es en texto — captura más la foto de la persona.', 'video/*,image/*', true,
   false, null, 'testimonios', null, null, null, 'fill',
   1, 1, 2042, '18 · Sube tus archivos', '', true),
  ('delegado_nombre', 'p19', 0, 10, 'Nombre de tu persona delegada', '', '', '', '', 'María José Ferrari',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2101, '19 · Tu delegado y tu comunicación', '', true),
  ('delegado_wa', 'p19', 0, 20, 'Su WhatsApp', '', '', '', '', '+54 9 341 555 9876',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, 'tel', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2102, '19 · Tu delegado y tu comunicación', '', true),
  ('delegado_horario', 'p19', 0, 30, '¿En qué horario suele estar disponible?', '', '', '', '', 'De 9 a 18h, hora Argentina',
   '[]'::jsonb, 'corta', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2103, '19 · Tu delegado y tu comunicación', '', true),
  ('compromiso', 'p19', 0, 40, 'Compromiso de respuesta', 'Las reglas del servicio piden respuestas rápidas — sobre todo en la etapa de grabación.', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"24","label":"Respondemos en menos de 24 h","hint":"Tú o tu delegado — lo que llegue primero"},{"value":"48","label":"Necesito hasta 48 h","hint":"Lo tendremos en cuenta en el cronograma"}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2104, '19 · Tu delegado y tu comunicación', '', true),
  ('imagen', 'p19', 0, 50, '¿Autorizas el uso de tu imagen y resultados en la comunicación de Korex?', 'Nace de cuidar tu marca: nunca publicamos nada tuyo sin tu permiso.', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, con mi consentimiento previo caso por caso","hint":""},{"value":"no","label":"No, mantener mi proyecto privado","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2105, '19 · Tu delegado y tu comunicación', '', true),
  ('grupo_reglas', 'p19', 0, 60, '¿Qué podemos publicar en tu grupo o comunidad y qué no?', 'Definirlo ahora evita malentendidos: separamos siempre el estado real de tu proyecto de cualquier comunicación comercial.', '', '', 'En el grupo del equipo pueden publicar avisos de capacitación y material de formación. No quiero que se publique nada de facturación ni de resultados de otras personas, ni promociones de Korex. Si hay algo comercial, me lo mandan a mí primero.', '',
   '[]'::jsonb, 'abierta', '[]'::jsonb, true, false, 0, 300, null, '', 110,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2106, '19 · Tu delegado y tu comunicación', '', true),
  ('info_20_0_0', 'p20', 0, 10, 'Mira el ejemplo de 40 segundos', '', '', '', '', '',
   '[]'::jsonb, 'info', '[]'::jsonb, false, false, 0, 0, null, '', null,
   'Antes de decidir', 'Mira el ejemplo de 40 segundos', 'Así se ve un cliente nuestro grabado una sola vez y después hablando en tres anuncios distintos, con distinto guion. No es un robot con tu cara: es tu grabación reutilizada.', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 2201, '20 · Tu grabación y HeyGen', '', true),
  ('heygen', 'p20', 0, 20, '¿Nos autorizas a usar HeyGen con tu imagen?', '', '', '', '', '',
   '[]'::jsonb, 'opciones', '[{"value":"si","label":"Sí, autorizo HeyGen","hint":"Generamos anuncios sin regrabar cada vez"},{"value":"no","label":"No, prefiero grabar todo manualmente","hint":""}]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   1, 1, 2202, '20 · Tu grabación y HeyGen', '', true),
  ('grabacion', 'p20', 0, 30, 'Reserva tu fecha firme de grabación', 'Necesitas una hora libre y un lugar con buena luz. Con el celular alcanza.', '', '', '', '',
   '[]'::jsonb, 'agenda', '[]'::jsonb, false, true, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   true, null, null, null, null, null, 'fill',
   1, 1, 2203, '20 · Tu grabación y HeyGen', '', true),
  ('qc', 'p21', 0, 10, '', '', '', '', '', '',
   '[]'::jsonb, 'resumen', '[]'::jsonb, false, false, 0, 0, null, '', null,
   '', '', '', '', '', '', true,
   false, null, null, null, null, null, 'fill',
   0, 1, 2301, '21 · Revisemos que no falte nada', '', true)
on conflict (qkey) do update set skey = excluded.skey, pantalla = excluded.pantalla, orden = excluded.orden,
  label = excluded.label, sublabel = excluded.sublabel, cabecera = excluded.cabecera,
  cabecera_sub = excluded.cabecera_sub, ejemplo = excluded.ejemplo, placeholder = excluded.placeholder,
  chips = excluded.chips, qtype = excluded.qtype, opciones = excluded.opciones,
  voz = excluded.voz, requerida = excluded.requerida, min_chars = 0,
  largo_objetivo = excluded.largo_objetivo, max_opciones = excluded.max_opciones,
  input_mode = excluded.input_mode, min_altura = excluded.min_altura,
  info_kicker = excluded.info_kicker, info_titulo = excluded.info_titulo, info_cuerpo = excluded.info_cuerpo,
  archivo_cta = excluded.archivo_cta, archivo_hint = excluded.archivo_hint,
  archivo_accept = excluded.archivo_accept, archivo_multiple = excluded.archivo_multiple,
  solo_dia = excluded.solo_dia, visible_si = excluded.visible_si,
  bucket_key = excluded.bucket_key, target_count = excluded.target_count,
  target_kind = excluded.target_kind, target_column = excluded.target_column,
  target_mode = excluded.target_mode, peso = excluded.peso,
  plantilla_ord = excluded.plantilla_ord, plantilla_ref = excluded.plantilla_ref,
  activa = true, updated_at = now()
 where public.onboarding_questions.updated_by is null;

-- ── 5 · Orden del documento, derivado ────────────────────────────────────────
update public.onboarding_questions q
   set plantilla_ord = s.orden * 1000 + q.pantalla * 20 + (q.orden / 10),
       plantilla_ref = s.badge || ' · ' || s.titulo,
       updated_at    = now()
  from public.onboarding_sections s
 where s.skey = q.skey and s.bkey is not null and q.activa;

commit;

notify pgrst, 'reload schema';
